# Generated by Django 4.0.5 on 2022-10-04 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=70, verbose_name='Имя')),
                ('tel_number', models.CharField(max_length=13, unique=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=50, unique=True, verbose_name='Почта клиента')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'db_table': 'clients',
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('surname', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('e_email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('experience', models.IntegerField(verbose_name='Стаж')),
                ('salary', models.IntegerField(verbose_name='Зарплата')),
                ('tel_number', models.CharField(max_length=13, verbose_name='Номер телефона')),
                ('position', models.CharField(choices=[('Admin', 'Администратор'), ('Chief', 'Начальник'), ('Detective', 'Детектив'), ('Assistant', 'Помощник детектива'), ('Manager', 'Менеджер')], max_length=30, verbose_name='Должность')),
                ('status', models.CharField(choices=[('Busy', 'Занят'), ('Available', 'Свободен')], max_length=30, verbose_name='Статус сотрудника')),
                ('chief', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agency_site.employees', verbose_name='Начальник')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'db_table': 'agency_employees',
                'ordering': ['salary'],
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_comment', models.TextField(default='', max_length=500, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('status', models.CharField(choices=[('Closed', 'Закрыта'), ('In process', 'На рассмотрении менеджера'), ('Pending client', 'На рассмотрении клиента'), ('Payed', 'Оплачена'), ('Rejected by client', 'Отклонена клиентом'), ('Rejected by manager', 'Отклонена менеджером'), ('In work', 'В работе')], default='In process', max_length=50, null=True, verbose_name='Статус заказа')),
                ('rate', models.IntegerField(default=1, null=True, verbose_name='Рейтинг')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency_site.clients', verbose_name='Клиент')),
                ('detective', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detective', to='agency_site.employees', verbose_name='Детектив')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='agency_site.employees', verbose_name='Менеджер')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='TypeOfOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Наблюдение', 'Наблюдение'), ('Сбор информации', 'Сбор информации'), ('Розыск человека', 'Розыск человека')], max_length=50, unique=True, verbose_name='Тип заказа')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('expected_days', models.IntegerField(verbose_name='Ожидаемое количество дней')),
            ],
            options={
                'verbose_name': 'Тип заказа',
                'verbose_name_plural': 'Типы заказов',
                'db_table': 'type_of_order',
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_date', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('task_description', models.TextField(max_length=500, verbose_name='Описание задания')),
                ('employees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency_site.employees', verbose_name='Детектив')),
                ('orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency_site.orders', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
                'db_table': 'tasks',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detective_report', models.TextField(max_length=500, verbose_name='Содержимое отчета')),
                ('report_date', models.DateField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency_site.orders', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Отчет',
                'verbose_name_plural': 'Отчеты',
                'db_table': 'report',
            },
        ),
        migrations.AddField(
            model_name='orders',
            name='type_of_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agency_site.typeoforder', verbose_name='Тип заказа'),
        ),
        migrations.CreateModel(
            name='Assistant_comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assistant_comments', models.TextField(max_length=500, verbose_name='Комментарий')),
                ('created_at', models.DateField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('employees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency_site.employees', verbose_name='Сотрудник')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency_site.tasks', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Комментарий помощника',
                'verbose_name_plural': 'Комментарии помощника',
                'db_table': 'assistant_comments',
            },
        ),
    ]
