# Generated by Django 4.0.5 on 2022-10-04 09:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='tel_number',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered. Up to 15 digits allowed.', regex='\\+38\\((050|063|067|093|096)\\)[0-9]{3}\\-[0-9]{2}\\-[0-9]{2}$')], verbose_name='Телефон'),
        ),
    ]
