# Generated by Django 4.0.5 on 2022-10-04 16:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_site', '0007_alter_clients_tel_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='tel_number',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in this format +38(096)0351321. Up to 13 digits allowed.', regex='^\\+38\\(\\050|063|067|093|096\\)\\d{7}$')], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Зарплата'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='tel_number',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in this format +38(096)0351321. Up to 13 digits allowed.', regex='^\\+38\\(\\050|063|067|093|096\\)\\d{7}$')], verbose_name='Номер телефона сотрудника'),
        ),
        migrations.AlterField(
            model_name='typeoforder',
            name='expected_days',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Ожидаемое количество дней'),
        ),
        migrations.AlterField(
            model_name='typeoforder',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=6, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Цена'),
        ),
    ]
