# Generated by Django 4.0.5 on 2022-10-04 17:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_site', '0009_alter_clients_tel_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='tel_number',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in this format +38(096)0351321. Up to 13 digits allowed.', regex='^\\\\+?[1-9][0-9]{7,14}$')], verbose_name='Телефон'),
        ),
    ]
