# Generated by Django 4.0.5 on 2022-10-05 09:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_site', '0011_alter_clients_tel_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='experience',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Стаж'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=8, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Зарплата'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='status',
            field=models.CharField(choices=[('Busy', 'Занят'), ('Available', 'Свободен')], default='Available', max_length=30, verbose_name='Статус сотрудника'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='tel_number',
            field=models.CharField(max_length=13, verbose_name='Номер телефона сотрудника'),
        ),
    ]
