# Generated by Django 4.0.5 on 2022-10-11 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency_site', '0012_alter_employees_experience_alter_employees_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='orders',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='agency_site.orders', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='employees',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency_site.employees', verbose_name='Помощник детектива'),
        ),
    ]
