# Generated by Django 4.0.5 on 2022-10-15 16:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_site', '0013_alter_report_orders_alter_tasks_employees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='tel_number',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in this format +380960351321. Up to 13 digits allowed.', regex='^\\+\\d{12}$')], verbose_name='Номер телефона сотрудника'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='client_comment',
            field=models.TextField(default='', max_length=250, null=True, verbose_name='Комментарий'),
        ),
    ]
