# Generated by Django 4.0.5 on 2022-10-15 16:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_site', '0014_alter_employees_tel_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='tel_number',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in this format +380960351321. Up to 13 digits allowed.', regex='^\\\\+?[1-9][0-9]{12,14}$')], verbose_name='Номер телефона сотрудника'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='client_comment',
            field=models.TextField(max_length=250, verbose_name='Комментарий'),
        ),
    ]
