# Generated by Django 4.0.5 on 2022-10-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_site', '0016_alter_clients_tel_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='client_comment',
            field=models.TextField(default='test', max_length=250, null=True, verbose_name='Комментарий'),
        ),
    ]
