# Generated by Django 4.0.5 on 2022-10-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_site', '0017_alter_orders_client_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='client_comment',
            field=models.TextField(max_length=250, verbose_name='Комментарий'),
        ),
    ]
