# Generated by Django 4.0.5 on 2022-10-17 08:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_site', '0022_alter_employees_tel_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='tel_number',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in this format +380960351321. Up to 13 digits allowed.', regex='\\+\\d{12}$')], verbose_name='Номер телефона сотрудника'),
        ),
    ]
