# Generated by Django 4.0.5 on 2022-10-17 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_site', '0023_alter_employees_tel_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='e_email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Почта'),
        ),
    ]
