# Generated by Django 4.0.5 on 2022-10-17 08:22

import agency_site.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_site', '0024_alter_employees_e_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='date_of_birth',
            field=models.DateField(validators=[agency_site.models.validate_date_not_in_future], verbose_name='Дата рождения'),
        ),
    ]
