# Generated by Django 4.0.5 on 2022-10-31 01:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_site', '0025_alter_employees_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='tel_number',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in this format +38(096)0351321. Up to 13 digits allowed.', regex='\\+\\d{12}$')], verbose_name='Телефон'),
        ),
    ]
